version: '3.0'

services:
    app:

      build: .

      image: jsm512/ossprac:3.0

      volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    production:

      image: jsm512/ossprac:3.0

      command: tiangolo/uwsgi-nginx-flask main.py

      ports:

        - '80:80'